name: Deploy Nightly
on:
  schedule:
    - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  nightly:
    name: Deploy Nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/mcpar-land/ivory/releases/52478105/assets{?name,label}
          release_id: 52478105
          asset_path: ./target/debug/ivory-repl.exe
          asset_name: ivory_windows-nightly-$$.exe
          asset_content_type: application/octet-stream
          max_releases: 1
      - name: Deploy Linux release
        if: matrix.os == 'ubuntu-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/mcpar-land/ivory/releases/52478105/assets{?name,label}
          release_id: 52478105
          asset_path: ./target/debug/ivory-repl
          asset_name: ivory_ubuntu-nightly-$$
          asset_content_type: application/octet-stream
          max_releases: 1
      - name: Deploy Mac OS release
        if: matrix.os == 'macOS-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/mcpar-land/ivory/releases/52478105/assets{?name,label}
          release_id: 52478105
          asset_path: ./target/debug/ivory-repl
          asset_name: ivory_macOS-nightly-$$
          asset_content_type: application/octet-stream
          max_releases: 1
        
          
